### ISSUE TITLE
Verify ALU

### ISSUE THREAD

**Issue by ogamespec** [emu-russia/dmgcpu#229]
Yeah, simple. Add a + b, make sure it works :)
Write a test run for Icarus to check it.
Let's NOT concentrate on the flag setting logic for now, it's complicated. Check CLA.

**Comment by ogamespec** [comment]
![image](https://github.com/emu-russia/dmgcpu/assets/5828819/8816302e-c146-4b70-a012-8009524620c7)

**Comment by ogamespec** [comment]
There seems to be extra carry crawling through all the guts somehow.

**Comment by ogamespec** [comment]
Took most of the ALU apart, but still 5+7 = 8 lol....

![image](https://github.com/emu-russia/dmgcpu/assets/5828819/e0249a5e-887b-468d-b08f-c3be4950c3aa)

Let's move on.

**Comment by ogamespec** [comment]
I suspect there's a bug somewhere in the Carry generator.

**Comment by ogamespec** [comment]
Better:
![image](https://github.com/emu-russia/dmgcpu/assets/5828819/d21b3c79-1fb9-4526-86b7-12055edb11ae)

But still not very well (77+35=144):
![image](https://github.com/emu-russia/dmgcpu/assets/5828819/17e0bff9-3721-457d-8955-ffe9fd31ed63)

**Comment by ogamespec** [comment]
![image](https://github.com/emu-russia/dmgcpu/assets/5828819/dfef2331-1108-4d70-a5d4-c45dc7637f85)

Issue in SET/RES/DAA random logic.

**Comment by ogamespec** [comment]
Fixed.
![image](https://github.com/emu-russia/dmgcpu/assets/5828819/c0569d78-95d9-4146-a891-f9c94a6bb4a8)

**Comment by ogamespec** [comment]
@Rodrigodd,

Hi, I fixed 2 bugs in ALU.v, you might be interested.

![image](https://github.com/emu-russia/dmgcpu/assets/5828819/fc399c70-7a89-4c9b-820d-a3fd6daf202c)

![image](https://github.com/emu-russia/dmgcpu/assets/5828819/90360fc0-1c16-4faf-9bd9-f9ca034ffb9d)

Now the ALU should be adding things up correctly :)

**Comment by Rodrigodd** [comment]
Good work! I should be able the test the ALU when progressing more in the `dmg-sim` integration. I am focusing in running dmg-sim's `quickboot.bin` for now, which is currently stuck in writing to memory (#239).

**Comment by ogamespec** [comment]
Closing this one :)
